import React, { useEffect, useState } from "react";
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";
import highchartsMap from "highcharts/modules/map";
import mapDataIE from "@highcharts/map-collection/countries/th/th-all.topo.json";

function Map({ dataa }) {
  const [chartData, setChartData] = useState([
   ["th-ct", 100],
          ["th-4255", 101],
          ["th-pg", 102],
          ["th-st", 103],
          ["th-kr", 104],
          ["th-sa", 105],
          ["th-tg", 106],
          ["th-tt", 107],
          ["th-pl", 108],
          ["th-ps", 109],
          ["th-kp", 200],
          ["th-pc", 201],
          ["th-sh", 202],
          ["th-at", 203],
          ["th-lb", 204],
          ["th-pa", 205],
          ["th-np", 206],
          ["th-sb", 207],
          ["th-cn", 208],
          ["th-bm", 6006],
          ["th-pt", 300],
          ["th-no", 301],
          ["th-sp", 3200],
          ["th-ss", 2600],
          ["th-sm", 304],
          ["th-pe", 305],
          ["th-cc", 306],
          ["th-nn", 307],
          ["th-cb", 308],
          ["th-br", 309],
          ["th-kk", 400],
          ["th-ph", 401],
          ["th-kl", 402],
          ["th-sr", 403],
          ["th-nr", 404],
          ["th-si", 405],
          ["th-re", 406],
          ["th-le", 407],
          ["th-nk", 408],
          ["th-ac", 409],
          ["th-md", 200],
          ["th-sn", 201],
          ["th-nw", 102],
          ["th-pi", 103],
          ["th-rn", 104],
          ["th-nt", 505],
          ["th-sg", 206],
          ["th-pr", 507],
          ["th-py", 508],
          ["th-so", 509],
          ["th-ud", 600],
          ["th-kn", 601],
          ["th-tk", 602],
          ["th-ut", 603],
          ["th-ns", 164],
          ["th-pk", 265],
          ["th-ur", 366],
          ["th-sk", 167],
          ["th-ry", 468],
          ["th-cy", 569],
          ["th-su", 370],
          ["th-nf", 571],
          ["th-bk", 772],
          ["th-mh", 873],
          ["th-pu", 374],
          ["th-cp", 975],
          ["th-yl", 976],
          ["th-cr", 577],
          ["th-cm", 478],
          ["th-ln", 379],
          ["th-na", 780],
          ["th-lg", 481],
          ["th-pb", 882],
          ["th-rt", 583],
          ["th-ys", 684],
          ["th-ms", 385],
          ["th-un", 386],
          ["th-nb", 687],
  ]);

  useEffect(() => {
    let newData;
    switch (dataa) {
      case "2":
        newData = [
          ["th-ct", 1120],
          ["th-4255", 1230],
          ["th-pg", 3240],
          ["th-st", 2113],
          ["th-kr", 3314],
          ["th-sa", 1115],
          ["th-tg", 3116],
          ["th-tt", 1217],
          ["th-pl", 2318],
          ["th-ps", 4219],
          ["th-kp", 15220],
          ["th-pc", 2221],
          ["th-sh", 3422],
          ["th-at", 3323],
          ["th-lb", 5524],
          ["th-pa", 4425],
          ["th-np", 3326],
          ["th-sb", 2227],
          ["th-cn", 1128],
          ["th-bm", 4429],
          ["th-pt", 2330],
          ["th-no", 2131],
          ["th-sp", 4432],
          ["th-ss", 5533],
          ["th-sm", 3334],
          ["th-pe", 6635],
          ["th-cc", 7736],
          ["th-nn", 8837],
          ["th-cb", 6638],
          ["th-br", 4439],
          ["th-kk", 5540],
          ["th-ph", 6641],
          ["th-kl", 7742],
          ["th-sr", 3343],
          ["th-nr", 2244],
          ["th-si", 1145],
          ["th-re", 4446],
          ["th-le", 5547],
          ["th-nk", 6648],
          ["th-ac", 7749],
          ["th-md", 8850],
          ["th-sn", 9951],
          ["th-nw", 5552],
          ["th-pi", 4453],
          ["th-rn", 1154],
          ["th-nt", 8855],
          ["th-sg", 2256],
          ["th-pr", 1157],
          ["th-py", 2258],
          ["th-so", 8859],
          ["th-ud", 6560],
          ["th-kn", 3461],
          ["th-tk", 6462],
          ["th-ut", 2363],
          ["th-ns", 5364],
          ["th-pk", 2365],
          ["th-ur", 5366],
          ["th-sk", 2167],
          ["th-ry", 1268],
          ["th-cy", 3269],
          ["th-su", 4270],
          ["th-nf", 1271],
          ["th-bk", 5472],
          ["th-mh", 4373],
          ["th-pu", 4374],
          ["th-cp", 3475],
          ["th-yl", 3476],
          ["th-cr", 4377],
          ["th-cm", 4378],
          ["th-ln", 2379],
          ["th-na", 4380],
          ["th-lg", 5381],
          ["th-pb", 1282],
          ["th-rt", 4383],
          ["th-ys", 5384],
          ["th-ms", 5685],
          ["th-un", 8786],
          ["th-nb", 9887],
        ];
        break;
      case "3":
        newData = [
          ["th-ct", 50],
          ["th-4255", 60],
          ["th-pg", 70],
          ["th-st", 13],
          ["th-kr", 14],
          ["th-sa", 15],
          ["th-tg", 16],
          ["th-tt", 17],
          ["th-pl", 18],
          ["th-ps", 19],
          ["th-kp", 20],
          ["th-pc", 21],
          ["th-sh", 22],
          ["th-at", 23],
          ["th-lb", 24],
          ["th-pa", 25],
          ["th-np", 26],
          ["th-sb", 27],
          ["th-cn", 28],
          ["th-bm", 29],
          ["th-pt", 30],
          ["th-no", 31],
          ["th-sp", 32],
          ["th-ss", 33],
          ["th-sm", 34],
          ["th-pe", 35],
          ["th-cc", 36],
          ["th-nn", 37],
          ["th-cb", 38],
          ["th-br", 39],
          ["th-kk", 40],
          ["th-ph", 41],
          ["th-kl", 42],
          ["th-sr", 43],
          ["th-nr", 44],
          ["th-si", 45],
          ["th-re", 46],
          ["th-le", 47],
          ["th-nk", 48],
          ["th-ac", 49],
          ["th-md", 50],
          ["th-sn", 51],
          ["th-nw", 52],
          ["th-pi", 53],
          ["th-rn", 54],
          ["th-nt", 55],
          ["th-sg", 56],
          ["th-pr", 57],
          ["th-py", 58],
          ["th-so", 59],
          ["th-ud", 60],
          ["th-kn", 61],
          ["th-tk", 62],
          ["th-ut", 63],
          ["th-ns", 64],
          ["th-pk", 65],
          ["th-ur", 66],
          ["th-sk", 67],
          ["th-ry", 68],
          ["th-cy", 69],
          ["th-su", 70],
          ["th-nf", 71],
          ["th-bk", 72],
          ["th-mh", 73],
          ["th-pu", 74],
          ["th-cp", 75],
          ["th-yl", 76],
          ["th-cr", 77],
          ["th-cm", 78],
          ["th-ln", 79],
          ["th-na", 80],
          ["th-lg", 81],
          ["th-pb", 82],
          ["th-rt", 83],
          ["th-ys", 84],
          ["th-ms", 85],
          ["th-un", 86],
          ["th-nb", 87],
        ];
        break;
      case "4":
        newData = [
          ["th-ct", 100],
          ["th-4255", 110],
          ["th-pg", 120],
          ["th-st", 13],
          ["th-kr", 14],
          ["th-sa", 15],
          ["th-tg", 16],
          ["th-tt", 17],
          ["th-pl", 18],
          ["th-ps", 19],
          ["th-kp", 20],
          ["th-pc", 21],
          ["th-sh", 22],
          ["th-at", 23],
          ["th-lb", 24],
          ["th-pa", 25],
          ["th-np", 26],
          ["th-sb", 27],
          ["th-cn", 28],
          ["th-bm", 29],
          ["th-pt", 30],
          ["th-no", 31],
          ["th-sp", 32],
          ["th-ss", 33],
          ["th-sm", 34],
          ["th-pe", 35],
          ["th-cc", 36],
          ["th-nn", 37],
          ["th-cb", 38],
          ["th-br", 39],
          ["th-kk", 40],
          ["th-ph", 41],
          ["th-kl", 42],
          ["th-sr", 43],
          ["th-nr", 44],
          ["th-si", 45],
          ["th-re", 46],
          ["th-le", 47],
          ["th-nk", 48],
          ["th-ac", 49],
          ["th-md", 50],
          ["th-sn", 51],
          ["th-nw", 52],
          ["th-pi", 53],
          ["th-rn", 54],
          ["th-nt", 55],
          ["th-sg", 56],
          ["th-pr", 57],
          ["th-py", 58],
          ["th-so", 59],
          ["th-ud", 60],
          ["th-kn", 61],
          ["th-tk", 62],
          ["th-ut", 63],
          ["th-ns", 64],
          ["th-pk", 65],
          ["th-ur", 66],
          ["th-sk", 67],
          ["th-ry", 68],
          ["th-cy", 69],
          ["th-su", 70],
          ["th-nf", 71],
          ["th-bk", 72],
          ["th-mh", 73],
          ["th-pu", 74],
          ["th-cp", 75],
          ["th-yl", 76],
          ["th-cr", 77],
          ["th-cm", 78],
          ["th-ln", 79],
          ["th-na", 80],
          ["th-lg", 81],
          ["th-pb", 82],
          ["th-rt", 83],
          ["th-ys", 84],
          ["th-ms", 85],
          ["th-un", 86],
          ["th-nb", 87],
        ];
        break;
      default:
        newData = [
          ["th-ct", 100],
          ["th-4255", 101],
          ["th-pg", 102],
          ["th-st", 103],
          ["th-kr", 104],
          ["th-sa", 105],
          ["th-tg", 106],
          ["th-tt", 107],
          ["th-pl", 108],
          ["th-ps", 109],
          ["th-kp", 200],
          ["th-pc", 201],
          ["th-sh", 202],
          ["th-at", 203],
          ["th-lb", 204],
          ["th-pa", 205],
          ["th-np", 206],
          ["th-sb", 207],
          ["th-cn", 208],
          ["th-bm", 6006],
          ["th-pt", 300],
          ["th-no", 301],
          ["th-sp", 3200],
          ["th-ss", 2600],
          ["th-sm", 304],
          ["th-pe", 305],
          ["th-cc", 306],
          ["th-nn", 307],
          ["th-cb", 308],
          ["th-br", 309],
          ["th-kk", 400],
          ["th-ph", 401],
          ["th-kl", 402],
          ["th-sr", 403],
          ["th-nr", 404],
          ["th-si", 405],
          ["th-re", 406],
          ["th-le", 407],
          ["th-nk", 408],
          ["th-ac", 409],
          ["th-md", 200],
          ["th-sn", 201],
          ["th-nw", 102],
          ["th-pi", 103],
          ["th-rn", 104],
          ["th-nt", 505],
          ["th-sg", 206],
          ["th-pr", 507],
          ["th-py", 508],
          ["th-so", 509],
          ["th-ud", 600],
          ["th-kn", 601],
          ["th-tk", 602],
          ["th-ut", 603],
          ["th-ns", 164],
          ["th-pk", 265],
          ["th-ur", 366],
          ["th-sk", 167],
          ["th-ry", 468],
          ["th-cy", 569],
          ["th-su", 370],
          ["th-nf", 571],
          ["th-bk", 772],
          ["th-mh", 873],
          ["th-pu", 374],
          ["th-cp", 975],
          ["th-yl", 976],
          ["th-cr", 577],
          ["th-cm", 478],
          ["th-ln", 379],
          ["th-na", 780],
          ["th-lg", 481],
          ["th-pb", 882],
          ["th-rt", 583],
          ["th-ys", 684],
          ["th-ms", 385],
          ["th-un", 386],
          ["th-nb", 687],
        ];
        break;
    }
    setChartData(newData);
  }, [dataa]);

  const mapOptions = {
    chart: {
      map: "th/th-all",
    },
    title: {
      text: "ตำแหน่งที่ผู้ใช้เรียกใช้งานมากที่สุด",
    },
    credits: {
      enabled: false,
    },
    mapNavigation: {
      enabled: true,
      buttonOptions: {
        verticalAlign: "center",
      },
    },
   
    tooltip: {
      headerFormat: "",
      pointFormat: "<b>{point.name}</b><br>มีทั้งหมด: <b>{point.value} คน</b>",
    },
    series: [
      {
        name: "Provinces",
        data: chartData.map(([code, value]) => ({ code, value,color: value > 500 ? "#1d8348" : value > 200 ? "#2ecc71" : "#abebc6", })),
        mapData: mapDataIE,
        joinBy: ["hc-key", "code"],
        states: {
          hover: {
            color: "#BADA55",
          },
        },
        dataLabels: {
          enabled: true,
          format: "{point.name}",
        },
        borderColor: "#A0A0A0",
        nullColor: "rgba(200, 200, 200, 0.3)",
        showInLegend: false,
      },
    ],
  };

  highchartsMap(Highcharts);

  return (
    <div className="map-container">
      <HighchartsReact
        constructorType={"mapChart"}
        highcharts={Highcharts}
        options={mapOptions}
      />
    </div>
  );
}

export default Map;

