const data = [
  {
    date: "1/21/2024",
    order_number: 21638495,
    username: "john.doe24",
    name: "John",
    surname: "Doe",
    phone_number: "0987654321",
    payment_method: "Credit Card",
    provider: "TowExpert Co.",
    provider_info: "Professional Towing Services",
    towcar_type: "Flatbed",
    provider_phone_number: "0823456789",
    price_service: 1500,
    review: "Excellent service, very quick.",
    status: "success",
  },
  {
    date: "8/20/2024",
    order_number: 92264758,
    username: "jane.smith88",
    name: "Jane",
    surname: "Smith",
    phone_number: "0912345678",
    payment_method: "Bank Transfer",
    provider: "FastTow Solutions",
    provider_info: "24/7 Roadside Assistance",
    towcar_type: "Hook and Chain",
    provider_phone_number: "0845671234",
    price_service: 1200,
    review: "Affordable price but took some time.",
    status: "success",
  },
  {
    date: "5/28/2024",
    order_number: 49623784,
    username: "alice.brown56",
    name: "Alice",
    surname: "Brown",
    phone_number: "0876543210",
    payment_method: "Cash",
    provider: "CityTow Experts",
    provider_info: "Reliable City-Wide Towing",
    towcar_type: "Integrated",
    provider_phone_number: "0897654321",
    price_service: 1800,
    review: "Good service overall.",
    status: "success",
  },
  {
    date: "7/6/2024",
    order_number: 33189674,
    username: "bob.williams32",
    name: "Bob",
    surname: "Williams",
    phone_number: "0865432190",
    payment_method: "Credit Card",
    provider: "Premium Tow Co.",
    provider_info: "Luxury Vehicle Specialists",
    towcar_type: "Wheel Lift",
    provider_phone_number: "0834567890",
    price_service: 2000,
    review: "Very professional, highly recommend.",
    status: "success",
  },
  {
    date: "10/27/2024",
    order_number: 33272894,
    username: "eve.johnson19",
    name: "Eve",
    surname: "Johnson",
    phone_number: "0854321678",
    payment_method: "PayPal",
    provider: "QuickTow Solutions",
    provider_info: "Rapid Towing Services",
    towcar_type: "Flatbed",
    provider_phone_number: "0823456712",
    price_service: 1400,
    review: "Average service, some delays.",
    status: "waiting",
  },
  {
    date: "10/25/2024",
    order_number: 86097456,
    username: "chris.martin23",
    name: "Chris",
    surname: "Martin",
    phone_number: "0843217654",
    payment_method: "Credit Card",
    provider: "Reliable Tow Inc.",
    provider_info: "Trusted Nationwide Services",
    towcar_type: "Hook and Chain",
    provider_phone_number: "0876543123",
    price_service: 1700,
    review: "Failed to arrive on time.",
    status: "failed",
  },
  {
    date: "9/15/2024",
    order_number: 24009876,
    username: "tom.harris44",
    name: "Tom",
    surname: "Harris",
    phone_number: "0891234567",
    payment_method: "Cash",
    provider: "CityTow Pros",
    provider_info: "Expert Urban Towing",
    towcar_type: "Wheel Lift",
    provider_phone_number: "0865432187",
    price_service: 1900,
    review: "Cancelled without notice.",
    status: "failed",
  },
  {
    date: "5/11/2024",
    order_number: 82283794,
    username: "sophia.miller77",
    name: "Sophia",
    surname: "Miller",
    phone_number: "0834567123",
    payment_method: "Credit Card",
    provider: "Nationwide Towing",
    provider_info: "From Coast to Coast",
    towcar_type: "Integrated",
    provider_phone_number: "0845678901",
    price_service: 1600,
    review: "On time and courteous driver.",
    status: "success",
  },
  {
    date: "6/20/2024",
    order_number: 74253789,
    username: "liam.anderson89",
    name: "Liam",
    surname: "Anderson",
    phone_number: "0812345698",
    payment_method: "Bank Transfer",
    provider: "FastTrack Towing",
    provider_info: "High-Speed Towing Services",
    towcar_type: "Flatbed",
    provider_phone_number: "0887654321",
    price_service: 1500,
    review: "Decent service but expensive.",
    status: "waiting",
  },
  {
    date: "8/9/2024",
    order_number: 21918374,
    username: "olivia.garcia25",
    name: "Olivia",
    surname: "Garcia",
    phone_number: "0809876543",
    payment_method: "Cash",
    provider: "Trusty Tow Service",
    provider_info: "Your Trusted Towing Partner",
    towcar_type: "Hook and Chain",
    provider_phone_number: "0854321765",
    price_service: 1300,
    review: "Excellent, fast response.",
    status: "success",
  },
  {
    date: "7/9/2024",
    order_number: 38654321,
    username: "noah.martinez76",
    name: "Noah",
    surname: "Martinez",
    phone_number: "0823456781",
    payment_method: "PayPal",
    provider: "Top Gear Tow",
    provider_info: "Premium Vehicle Towing",
    towcar_type: "Integrated",
    provider_phone_number: "0891234675",
    price_service: 1400,
    review: "Very satisfied with the service.",
    status: "success",
  },
  {
    date: "12/1/2024",
    order_number: 71932485,
    username: "mia.davis55",
    name: "Mia",
    surname: "Davis",
    phone_number: "0872341256",
    payment_method: "Credit Card",
    provider: "SureTow Services",
    provider_info: "Reliable Nationwide Coverage",
    towcar_type: "Flatbed",
    provider_phone_number: "0891234987",
    price_service: 1450,
    review: "Service was good but expensive.",
    status: "waiting",
  },
  {
    date: "11/15/2024",
    order_number: 69237485,
    username: "william.lee33",
    name: "William",
    surname: "Lee",
    phone_number: "0851234567",
    payment_method: "Bank Transfer",
    provider: "Global Tow Co.",
    provider_info: "Fast and Friendly Service",
    towcar_type: "Wheel Lift",
    provider_phone_number: "0865431298",
    price_service: 1350,
    review: "Driver was courteous.",
    status: "success",
  },
  {
    date: "10/5/2024",
    order_number: 49857623,
    username: "ella.thomas99",
    name: "Ella",
    surname: "Thomas",
    phone_number: "0892345123",
    payment_method: "Cash",
    provider: "Super Tow Services",
    provider_info: "24/7 Reliable Tow Service",
    towcar_type: "Hook and Chain",
    provider_phone_number: "0812345987",
    price_service: 1250,
    review: "Affordable but took longer than expected.",
    status: "failed",
  },
  {
    date: "9/28/2024",
    order_number: 57328495,
    username: "james.clark22",
    name: "James",
    surname: "Clark",
    phone_number: "0819876543",
    payment_method: "PayPal",
    provider: "Quick Towline",
    provider_info: "Affordable Towing Solutions",
    towcar_type: "Flatbed",
    provider_phone_number: "0887541236",
    price_service: 1100,
    review: "Fast and reliable service.",
    status: "success",
  },
  {
    date: "8/11/2024",
    order_number: 37291846,
    username: "emily.morris11",
    name: "Emily",
    surname: "Morris",
    phone_number: "0801234976",
    payment_method: "Credit Card",
    provider: "Rapid Tow Now",
    provider_info: "High-Speed Towing Services",
    towcar_type: "Integrated",
    provider_phone_number: "0876532149",
    price_service: 1900,
    review: "Excellent service overall.",
    status: "success",
  },
  {
    date: "7/5/2024",
    order_number: 98643257,
    username: "logan.white98",
    name: "Logan",
    surname: "White",
    phone_number: "0891234789",
    payment_method: "Cash",
    provider: "TowKing Services",
    provider_info: "Trusted Name in Towing",
    towcar_type: "Wheel Lift",
    provider_phone_number: "0863421578",
    price_service: 1400,
    review: "Fast service but expensive.",
    status: "waiting",
  },
  {
    date: "6/19/2024",
    order_number: 32845719,
    username: "isabella.hall44",
    name: "Isabella",
    surname: "Hall",
    phone_number: "0887654321",
    payment_method: "Bank Transfer",
    provider: "Friendly Tow Co.",
    provider_info: "Best Towing Experience",
    towcar_type: "Hook and Chain",
    provider_phone_number: "0854321789",
    price_service: 1550,
    review: "Average experience.",
    status: "success",
  },
  {
    date: "5/21/2024",
    order_number: 48573129,
    username: "lucas.young67",
    name: "Lucas",
    surname: "Young",
    phone_number: "0812345987",
    payment_method: "Credit Card",
    provider: "SafeTow Services",
    provider_info: "Safety First in Towing",
    towcar_type: "Flatbed",
    provider_phone_number: "0845672198",
    price_service: 1650,
    review: "Reliable and professional.",
    status: "success",
  },
  {
    date: "4/30/2024",
    order_number: 19283746,
    username: "sophia.wood90",
    name: "Sophia",
    surname: "Wood",
    phone_number: "0809876543",
    payment_method: "PayPal",
    provider: "TrustTow Co.",
    provider_info: "Top Rated Towing Services",
    towcar_type: "Integrated",
    provider_phone_number: "0834521796",
    price_service: 1750,
    review: "Satisfied with the service.",
    status: "success",
  },
];

export default data;
